name: aula9total
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  android_alarm_manager_plus: ^4.0.3
  flutter:
    sdk: flutter
  http: ^1.2.1
  logger: ^2.3.0
  permission_handler: ^11.3.1
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
